/**
 * ejercicio1
Crear una clase "Rectángulo" con métodos para calcular el área y el perímetro de un rectángulo.
Crear la clase "Rectangulo" con los atributos "ancho" y "altura".
Implementar el método "calcularArea()" que devuelve el área del rectángulo.
Implementar el método "calcularPerimetro()" que devuelve el perímetro del rectángulo.
 */




/**
 *ejercicio 2 
 *  Crear una clase "CuentaBancaria" con métodos para gestionar una cuenta con saldo, depósitos y retiros.
Crear la clase "CuentaBancaria" con el atributo "saldo".
Implementar el método "depositar(cantidad)" que incrementa el saldo de la cuenta.
Implementar el método "retirar(cantidad)" que disminuye el saldo de la cuenta si hay fondos suficientes.
Implementar el método "consultarSaldo()" que muestra el saldo actual de la cuenta.

 */